# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da546f41b5fce1e90c72b05fd5df85d2e5c4a920d7925812427192e4a5ecb0743f01b61050c607e36f4b0e400c927cfcf3f55558d9cf195786b2a691417ea935

test:
  secret_key_base: d4b92e79b1aba812a2a65cf690242f2dab68aa163ebc4bea6355cf1668e23595c66acc7042ae21a9558d44a01ca1af3ca249bf5d79e99a237513c2aff4741302

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
